-- ============================================================
-- ConForum -- Supabase PostgreSQL Schema
-- Version: 2.2
--
-- Changelog from v2.1:
--   - conferences: organizer_id ON DELETE SET NULL already
--     correct. No structural change needed for the admin
--     organizer assignment fix — that is handled entirely
--     in application logic (createConferenceController).
--   - research_papers: ON DELETE SET NULL on conference_id
--     is intentional. Application logic in
--     deleteConferenceController now explicitly deletes
--     papers and their storage files before deleting the
--     conference, so orphaned papers never occur in practice.
--   - No new columns in this version. All fixes in v2.2 are
--     application-layer only (controller + frontend changes).
--
-- How to use:
--   Run this entire file in the Supabase SQL Editor on a fresh
--   database. If your database already exists, scroll to the
--   bottom "Safe Migrations" section and run only those ALTER
--   statements instead of dropping and recreating.
--
-- Notes:
--   - RLS is intentionally disabled on all tables. The backend
--     communicates via the service-role key which bypasses RLS
--     anyway. Add RLS policies later if you need client-side
--     row-level security.
--   - All primary keys are UUID generated by gen_random_uuid().
--   - TIMESTAMPTZ is used for all timestamps (UTC stored,
--     any timezone can be read back).
-- ============================================================


-- ============================================================
-- TABLE: users
-- Core user accounts for authors, organizers, and admins.
-- role = 0 means a regular user; role = 1 means admin.
-- recovery_key is a bcrypt-hashed phrase set at registration
-- and used as the second factor in the forgot-password flow
-- (no OTP required for password reset).
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id            UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name          TEXT        NOT NULL,
  email         TEXT        NOT NULL UNIQUE,
  password      TEXT        NOT NULL,
  phone         TEXT        NOT NULL,
  address       TEXT        NOT NULL,
  recovery_key  TEXT        NOT NULL,
  -- 0 = regular user, 1 = admin
  role          INTEGER     NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: reviewers
-- Separate reviewer accounts created through the legacy
-- reviewer-register flow (reviewerController.js).
-- The main invitation flow uses user_conference_roles instead,
-- so this table will always be empty in production and is kept
-- only for backward compatibility. Do not use for new features.
-- expertise is an array of keyword strings.
-- ============================================================
CREATE TABLE IF NOT EXISTS reviewers (
  id        UUID    NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name      TEXT    NOT NULL,
  email     TEXT    NOT NULL UNIQUE,
  password  TEXT    NOT NULL,
  expertise TEXT[]  NOT NULL DEFAULT '{}'
);


-- ============================================================
-- TABLE: conferences
-- One row per conference. The organizer who creates it is
-- stored in organizer_id (FK to users) as well as denormalised
-- name/email columns so the organizer info is readable even if
-- the user account is later deleted.
--
-- When an admin creates a conference they must supply an
-- organizerEmail in the request body. createConferenceController
-- resolves that email to a user and stores that user's id/name/
-- email here — never the admin's own id.
--
-- mode controls the review blind policy:
--   "single-blind" | "double-blind" | "open"
--
-- status lifecycle:
--   "pending" -> "approved" | "rejected"
--
-- max_resubmissions: NULL means unlimited resubmissions;
--   a positive integer caps how many times a paper may be
--   resubmitted before the final decision.
--
-- proceedings_pdf_url: set after the organizer generates the
--   proceedings PDF via proceedingsPdfGenerationController.
-- ============================================================
CREATE TABLE IF NOT EXISTS conferences (
  id                   UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  conference_name      TEXT        NOT NULL,
  -- Short identifier used in URLs and submission links (must be unique)
  acronym              TEXT        NOT NULL UNIQUE,
  web_page             TEXT,
  -- Review blind mode: "single-blind" | "double-blind" | "open"
  mode                 TEXT,
  venue                TEXT,
  city                 TEXT,
  country              TEXT,
  start_date           DATE,
  end_date             DATE,
  abstract_deadline    DATE,
  submission_deadline  DATE,
  primary_area         TEXT,
  secondary_area       TEXT,
  -- Free-form topic tags for the conference
  topics               TEXT[]      DEFAULT '{}',
  -- Required expertise keywords used when inviting reviewers
  expertise            TEXT[]      DEFAULT '{}',
  -- Lifecycle status: "pending" | "approved" | "rejected"
  status               TEXT        NOT NULL DEFAULT 'pending',
  -- Auto-generated public URL for paper submissions
  submission_link      TEXT,
  -- Denormalised organizer fields so info is readable without a join.
  -- ON DELETE SET NULL so conference row survives if organizer account
  -- is deleted — organizer_name and organizer_email still readable.
  organizer_id         UUID        REFERENCES users (id) ON DELETE SET NULL,
  organizer_name       TEXT,
  organizer_email      TEXT,
  -- Set after the proceedings PDF is generated and uploaded to storage
  proceedings_pdf_url  TEXT,
  -- NULL = unlimited; positive integer caps per-paper resubmissions
  max_resubmissions    INTEGER     DEFAULT NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: user_conference_roles
-- Junction table that assigns a role to a user within a
-- specific conference. One row per (user, conference, role).
--
-- Possible roles: "author" | "reviewer" | "organizer"
--
-- Special case -- organizer invitation pending:
--   conference_id is NULL while the organizer has accepted the
--   invitation but has not yet created their conference.
--   Once the conference is created, the NULL row is replaced by
--   a row with the real conference_id.
--
-- When an admin creates a conference with an organizerEmail,
--   createConferenceController inserts a row here for the
--   resolved organizer user directly (no NULL placeholder needed
--   because the conference already exists at insert time).
--
-- expertise is only populated when role = 'reviewer'.
--
-- The unique constraint on (user_id, conference_id, role)
-- prevents duplicate role assignments. Note: because
-- conference_id can be NULL (for pending organizers), two NULL
-- rows for the same user would NOT be caught by this constraint
-- in standard SQL. Application logic handles that edge case.
-- ============================================================
CREATE TABLE IF NOT EXISTS user_conference_roles (
  id             UUID   NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id        UUID   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  -- NULL only for organizers awaiting conference creation
  conference_id  UUID   REFERENCES conferences (id) ON DELETE CASCADE,
  -- "author" | "reviewer" | "organizer"
  role           TEXT   NOT NULL,
  -- Reviewer expertise keywords; empty array for non-reviewer roles
  expertise      TEXT[] DEFAULT '{}',
  UNIQUE (user_id, conference_id, role)
);


-- ============================================================
-- TABLE: invitations
-- Token-based invitation records for both organizer and
-- reviewer invitation flows.
--
-- conference_id is NULL for organizer invitations because the
-- conference does not yet exist when the admin sends the invite.
--
-- token is a UUID generated by crypto.randomUUID() and is
-- embedded in the invitation link so the email address is
-- never exposed in the URL.
--
-- user_id is populated when an existing user responds to an
-- invitation via respondToInvitationController — it is NULL
-- for recipients who have not yet registered.
--
-- status lifecycle: "pending" -> "accepted" | "declined"
-- ============================================================
CREATE TABLE IF NOT EXISTS invitations (
  id             UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  -- Populated after the invited person registers or logs in
  user_id        UUID        REFERENCES users (id) ON DELETE SET NULL,
  email          TEXT        NOT NULL,
  -- NULL for organizer invitations (conference not yet created)
  conference_id  UUID        REFERENCES conferences (id) ON DELETE CASCADE,
  -- "organizer" | "reviewer"
  role           TEXT        NOT NULL DEFAULT 'reviewer',
  -- "pending" | "accepted" | "declined"
  status         TEXT        NOT NULL DEFAULT 'pending',
  -- Unique random UUID embedded in the invitation link
  token          TEXT        UNIQUE,
  invited_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: login_otps
-- One-time 6-digit codes sent to users during the login flow.
-- A user must pass credential check first; the OTP is the
-- second factor before a JWT is issued.
--
-- used = TRUE after the code is consumed by verifyOtpController
--   so that replay attacks are prevented.
-- expires_at is set to NOW() + 10 minutes at creation time.
-- ============================================================
CREATE TABLE IF NOT EXISTS login_otps (
  id          UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  otp_code    TEXT        NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  -- Set to TRUE when the code is successfully verified
  used        BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: authors
-- Author metadata collected at paper submission time.
-- An author record is reused across submissions if the same
-- email already exists (bulk-fetch + insert in
-- submitPaperController avoids N+1 queries).
--
-- user_id links the author record back to the registered user
-- who submitted the paper. It is NULL for co-authors who do
-- not have a ConForum account.
--
-- corresponding_author flags the primary contact for the paper.
-- ============================================================
CREATE TABLE IF NOT EXISTS authors (
  id                    UUID    NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  first_name            TEXT    NOT NULL,
  last_name             TEXT,
  email                 TEXT    NOT NULL,
  country               TEXT,
  affiliation           TEXT,
  web_page              TEXT,
  -- TRUE for the author designated as the main contact
  corresponding_author  BOOLEAN NOT NULL DEFAULT FALSE,
  -- NULL for co-authors without a ConForum account
  user_id               UUID    REFERENCES users (id) ON DELETE SET NULL
);


-- ============================================================
-- TABLE: research_papers
-- One row per submitted paper.
--
-- status lifecycle:
--   "pending" -> "assigned" -> "reviewed" -> (decision set)
--   On resubmission the status resets to "resubmitted" and then
--   goes through "assigned" -> "reviewed" again.
--
-- final_decision values (set by organizer):
--   "Accepted" | "Rejected" | "Modification Required" | NULL
--   When "Modification Required" the status is also reset to
--   "pending" so the author can resubmit.
--
-- compliance_report: JSONB blob written by the Flask IEEE
--   compliance service. Schema: { percentage, details[] }
--   Initialised with a "Pending" placeholder at submission time
--   and updated asynchronously once the Flask check completes.
--
-- plagiarism_report: reserved JSONB field for future use.
--   Schema: { score, isAIGenerated }
--
-- organizer_plagiarism_score: a 0-100 numeric score manually
--   entered by the organizer. Papers without this score cannot
--   be auto-assigned to reviewers (enforced in
--   assignPapersToReviewersController and
--   manuallyAssignPaperController).
--
-- organizer_comments_for_authors: optional free-text feedback
--   written by the organizer when reviewing a paper directly
--   (bypassing the reviewer flow). Shown to authors after the
--   decision is published. Set by updateFinalDecisionController.
--
-- resubmission_count: incremented each time the author
--   resubmits. Checked against conferences.max_resubmissions.
--
-- conference_id uses ON DELETE SET NULL intentionally.
--   deleteConferenceController explicitly deletes all papers
--   (and their storage files) before deleting the conference,
--   so this column should never actually become NULL in
--   practice. The SET NULL is a safety net only.
--
-- conference_name / conference_acronym: denormalised so that
--   paper listings remain readable after a conference is renamed
--   or deleted.
-- ============================================================
CREATE TABLE IF NOT EXISTS research_papers (
  id                              UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title                           TEXT,
  abstract                        TEXT,
  keywords                        TEXT[]      DEFAULT '{}',
  -- Supabase Storage public URL for the uploaded PDF
  paper_file_path                 TEXT,
  -- SET NULL safety net; controller deletes papers before conference
  conference_id                   UUID        REFERENCES conferences (id) ON DELETE SET NULL,
  -- Denormalised conference identifiers for display without a join
  conference_name                 TEXT,
  conference_acronym              TEXT,
  -- "pending" | "resubmitted" | "assigned" | "reviewed"
  status                          TEXT        NOT NULL DEFAULT 'pending',
  -- NULL until the organizer makes a decision
  -- "Accepted" | "Rejected" | "Modification Required"
  final_decision                  TEXT        DEFAULT NULL,
  -- IEEE compliance result from the Flask service
  compliance_report               JSONB       NOT NULL DEFAULT '{"percentage": 0, "details": []}',
  -- Reserved for future plagiarism/AI detection integration
  plagiarism_report               JSONB       NOT NULL DEFAULT '{"score": 0, "isAIGenerated": false}',
  -- Manually entered by the organizer before reviewer assignment (0-100)
  organizer_plagiarism_score      NUMERIC     DEFAULT NULL,
  -- Optional organizer feedback shown to authors after the decision
  -- is published. NULL when paper went through normal reviewer flow.
  organizer_comments_for_authors  TEXT        DEFAULT NULL,
  -- How many times this paper has been resubmitted
  resubmission_count              INTEGER     NOT NULL DEFAULT 0,
  created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: paper_authors
-- Junction table linking research_papers to authors.
-- Composite primary key prevents duplicate linkings.
-- Cascade deletes clean up orphan rows when a paper or author
-- is removed.
-- ============================================================
CREATE TABLE IF NOT EXISTS paper_authors (
  paper_id   UUID NOT NULL REFERENCES research_papers (id) ON DELETE CASCADE,
  author_id  UUID NOT NULL REFERENCES authors (id) ON DELETE CASCADE,
  PRIMARY KEY (paper_id, author_id)
);


-- ============================================================
-- TABLE: assignments
-- Tracks which reviewer has been assigned to which paper for
-- a given conference.
--
-- Business rule enforced in application logic:
--   A maximum of 3 reviewers may be assigned per paper.
--
-- reviewer_id references users (not reviewers) because all
-- invited reviewers are stored in the users table via the
-- invitation flow. The legacy reviewers table is not used.
--
-- assigned_at records when the assignment was created, which
-- is surfaced in the reviewer portal
-- (getAssignedPapersForReviewerController).
--
-- The unique constraint on (paper_id, reviewer_id) prevents
-- the same reviewer from being assigned to the same paper twice.
-- ============================================================
CREATE TABLE IF NOT EXISTS assignments (
  id             UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  paper_id       UUID        NOT NULL REFERENCES research_papers (id) ON DELETE CASCADE,
  -- FK to users (not reviewers) — invited reviewers live in users table
  reviewer_id    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  conference_id  UUID        NOT NULL REFERENCES conferences (id) ON DELETE CASCADE,
  assigned_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (paper_id, reviewer_id)
);


-- ============================================================
-- TABLE: reviews
-- One review per (paper, reviewer) pair. A reviewer may have
-- their review deleted and re-submit when a paper is resubmitted
-- (updatePaperController deletes all reviews on resubmit so
-- the reviewer portal shows the paper as "pending" again).
--
-- Scoring fields (originality, technical_quality, significance,
-- clarity, relevance) are integer ratings 1-10 supplied by the
-- reviewer via the review form.
--
-- technical_confidence is a weighted composite score calculated
-- server-side using the conference's technical_weightage settings:
--   (originality * w_orig + technical_quality * w_tq + ...) / 100
--
-- overall_recommendation values used in the app:
--   "Accept" | "Accept with minor correction" | "Reject"
--
-- comments_for_authors: visible to the paper authors.
-- comments_for_organizers: visible only to the organizer.
-- ============================================================
CREATE TABLE IF NOT EXISTS reviews (
  id                       UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  paper_id                 UUID        NOT NULL REFERENCES research_papers (id) ON DELETE CASCADE,
  -- FK to users (the reviewer's main user account)
  reviewer_id              UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  -- Reviewer-supplied integer scores (1-10)
  originality              INTEGER,
  technical_quality        INTEGER,
  significance             INTEGER,
  clarity                  INTEGER,
  relevance                INTEGER,
  -- "Accept" | "Accept with minor correction" | "Reject"
  overall_recommendation   TEXT,
  -- Shown to authors
  comments_for_authors     TEXT,
  -- Shown only to the organizer
  comments_for_organizers  TEXT,
  -- Weighted composite score calculated at submission time
  technical_confidence     NUMERIC,
  reviewed_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: technical_weightage
-- Per-conference weighting for the five review criteria.
-- Weights must sum to 100 (enforced in application logic by
-- setTechnicalWeightageController).
-- Used by submitReviewFormController to compute
-- technical_confidence from the raw reviewer scores.
--
-- Default weights (applied when no row exists for a conference):
--   originality=30, technical_quality=25, significance=20,
--   clarity=15, relevance=10
-- ============================================================
CREATE TABLE IF NOT EXISTS technical_weightage (
  id                UUID    NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  -- One row per conference; updating uses upsert on conference_id
  conference_id     UUID    NOT NULL UNIQUE REFERENCES conferences (id) ON DELETE CASCADE,
  originality       INTEGER NOT NULL DEFAULT 30,
  technical_quality INTEGER NOT NULL DEFAULT 25,
  significance      INTEGER NOT NULL DEFAULT 20,
  clarity           INTEGER NOT NULL DEFAULT 15,
  relevance         INTEGER NOT NULL DEFAULT 10
);


-- ============================================================
-- INDEXES
-- Additional indexes beyond the implicit primary-key indexes.
-- Named with a consistent "idx_<table>_<column(s)>" convention.
-- ============================================================

-- user_conference_roles — frequently filtered by all three columns
CREATE INDEX IF NOT EXISTS idx_ucr_user
  ON user_conference_roles (user_id);

CREATE INDEX IF NOT EXISTS idx_ucr_conference
  ON user_conference_roles (conference_id);

CREATE INDEX IF NOT EXISTS idx_ucr_role
  ON user_conference_roles (role);

-- research_papers — most queries filter by conference
CREATE INDEX IF NOT EXISTS idx_papers_conference
  ON research_papers (conference_id);

-- research_papers — status-filtered queries (pending, assigned, etc.)
CREATE INDEX IF NOT EXISTS idx_papers_status
  ON research_papers (status);

-- research_papers — decision-filtered queries (accepted papers for proceedings)
CREATE INDEX IF NOT EXISTS idx_papers_final_decision
  ON research_papers (final_decision);

-- assignments — join patterns from all three directions
CREATE INDEX IF NOT EXISTS idx_assignments_paper
  ON assignments (paper_id);

CREATE INDEX IF NOT EXISTS idx_assignments_reviewer
  ON assignments (reviewer_id);

CREATE INDEX IF NOT EXISTS idx_assignments_conference
  ON assignments (conference_id);

-- reviews — lookups by paper and by reviewer
CREATE INDEX IF NOT EXISTS idx_reviews_paper
  ON reviews (paper_id);

CREATE INDEX IF NOT EXISTS idx_reviews_reviewer
  ON reviews (reviewer_id);

-- invitations — lookup by email (registration check) and token (link validation)
CREATE INDEX IF NOT EXISTS idx_invitations_email
  ON invitations (email);

CREATE INDEX IF NOT EXISTS idx_invitations_token
  ON invitations (token);

-- login_otps — lookup by user_id when verifying the submitted code
CREATE INDEX IF NOT EXISTS idx_login_otps_user
  ON login_otps (user_id);

-- paper_authors — join from both directions
CREATE INDEX IF NOT EXISTS idx_paper_authors_paper
  ON paper_authors (paper_id);

CREATE INDEX IF NOT EXISTS idx_paper_authors_author
  ON paper_authors (author_id);

-- authors — lookup by email during submission (upsert check)
CREATE INDEX IF NOT EXISTS idx_authors_email
  ON authors (email);

-- authors — lookup by user_id in getUserConferencePapersController
CREATE INDEX IF NOT EXISTS idx_authors_user
  ON authors (user_id);

-- conferences — status filter used by pending/approved/rejected endpoints
CREATE INDEX IF NOT EXISTS idx_conferences_status
  ON conferences (status);

-- conferences — acronym lookup used by getConferenceByAcronymController
CREATE INDEX IF NOT EXISTS idx_conferences_acronym
  ON conferences (acronym);


-- ============================================================
-- SAFE MIGRATIONS
-- Run ONLY these statements if the database already exists and
-- you do not want to recreate it from scratch. Each statement
-- is idempotent (IF NOT EXISTS guards).
--
-- These cover every column added after the original schema was
-- deployed, derived from a full audit of all controllers.
-- ============================================================

-- invitations: token column added for token-based invite links
ALTER TABLE invitations
  ADD COLUMN IF NOT EXISTS token TEXT UNIQUE;

-- invitations: user_id column added for respondToInvitationController
ALTER TABLE invitations
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users (id) ON DELETE SET NULL;

-- research_papers: organizer-entered plagiarism score (0-100)
ALTER TABLE research_papers
  ADD COLUMN IF NOT EXISTS organizer_plagiarism_score NUMERIC DEFAULT NULL;

-- research_papers: tracks how many times a paper has been resubmitted
ALTER TABLE research_papers
  ADD COLUMN IF NOT EXISTS resubmission_count INTEGER NOT NULL DEFAULT 0;

-- research_papers: final editorial decision by the organizer
ALTER TABLE research_papers
  ADD COLUMN IF NOT EXISTS final_decision TEXT DEFAULT NULL;

-- research_papers: reserved JSONB field for plagiarism/AI detection
ALTER TABLE research_papers
  ADD COLUMN IF NOT EXISTS plagiarism_report JSONB NOT NULL DEFAULT '{"score": 0, "isAIGenerated": false}';

-- research_papers: denormalised conference acronym for display without join
ALTER TABLE research_papers
  ADD COLUMN IF NOT EXISTS conference_acronym TEXT;

-- research_papers: optional organizer feedback shown to authors after
-- decision. Used by updateFinalDecisionController when organizer reviews
-- a paper directly via the "Review Myself" flow in AssignPapersPage.
ALTER TABLE research_papers
  ADD COLUMN IF NOT EXISTS organizer_comments_for_authors TEXT DEFAULT NULL;

-- reviews: timestamp for when the review was submitted
ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- reviews: organizer-only feedback field
ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS comments_for_organizers TEXT;

-- conferences: admin-configurable resubmission limit per paper
ALTER TABLE conferences
  ADD COLUMN IF NOT EXISTS max_resubmissions INTEGER DEFAULT NULL;

-- conferences: URL to the generated proceedings PDF
ALTER TABLE conferences
  ADD COLUMN IF NOT EXISTS proceedings_pdf_url TEXT;

-- conferences: review blind mode ("single-blind" | "double-blind" | "open")
ALTER TABLE conferences
  ADD COLUMN IF NOT EXISTS mode TEXT;

-- user_conference_roles: expertise array for reviewer roles
ALTER TABLE user_conference_roles
  ADD COLUMN IF NOT EXISTS expertise TEXT[] DEFAULT '{}';

-- assignments: timestamp used in reviewer portal listing
ALTER TABLE assignments
  ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- authors: web page URL collected during paper submission
ALTER TABLE authors
  ADD COLUMN IF NOT EXISTS web_page TEXT;

-- authors: link back to the submitting user account
ALTER TABLE authors
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users (id) ON DELETE SET NULL;

  ALTER TABLE assignments
ADD COLUMN due_date TIMESTAMPTZ;  -- stores UTC, nullable